services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/collar-bud?schema=public
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./next.config.mjs
          action: rebuild
        - path: .
          target: /app
          action: sync
    volumes:
      - collar-bud:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collar-bud
    volumes:
      - collar-bud-db:/var/lib/postgresql/data
    restart: always
volumes:
  collar-bud:
  collar-bud-db:
